import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { CartProvider } from "@/components/cart/CartContext";
import CartPanel from "@/components/cart/CartPanel";
import { QuickViewProvider } from "@/components/product/QuickViewContext";
import QuickViewModal from "@/components/product/QuickViewModal";
import { WishlistProvider } from "@/components/wishlist/WishlistContext";
import Intro from "@/components/intro/Intro";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-intro="true"
    >
      <body className="min-h-full flex flex-col">
        <Intro />
        <WishlistProvider>
          <CartProvider>
            <QuickViewProvider>
              <Header />
              <div className="flex-1">
                {children}
              </div>
              <Footer />
              <CartPanel />
              <QuickViewModal />
            </QuickViewProvider>
          </CartProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}
